name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ">=14"

      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Install
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
